# config/routes.yaml


#Routes for the navbar links##########################
home:
  path: /
  controller: App\Controller\MainController::home

about:
  path: /about
  controller: App\Controller\MainController::about


discount:
  path: /discount
  controller: App\Controller\MainController::discount

support:
  path: /support
  controller: App\Controller\MainController::support
#######################################################

##############Routes for the admin page################
adminIndex:
  path: /admin
  controller: App\Controller\AdminController::adminIndex

adminEdit:
  path: /admin/edit
  controller: App\Controller\AdminController::edit

adminDelete:
  path: /admin/delete
  controller: App\Controller\AdminController::delete

adminAdd:
  path: /admin/add
  controller: App\Controller\AdminController::add

#######################################################


########Routes for the login / registration and logout#######

security_login:
  path: /login
  controller: App\Controller\SecurityController::login

security_logout:
  path: /logout
  methods: GET

security_register:
  path: /register
  controller: App\Controller\SecurityController::register

user_profile:
  path: /profile
  controller: App\Controller\AuthController::profile

#########Subcategories routes (IT)###############################

categories:
  path: /products
  controller: App\Controller\ProductsController::category

subcategories:
  path: /products/{name}
  controller: App\Controller\ProductsController::subcategory

items:
  path: /products/{category}/{name}
  controller: App\Controller\ProductsController::items