# config/routes.yaml


#Routes for the navbar links##########################
home:
  path: /
  controller: App\Controller\MainController::home

about:
  path: /about
  controller: App\Controller\MainController::about

products:
  path: /products
  controller: App\Controller\MainController::products

discount:
  path: /discount
  controller: App\Controller\MainController::discount

support:
  path: /support
  controller: App\Controller\MainController::support
#######################################################

##############Routes for the admin page################
adminIndex:
  path: /admin
  controller: App\Controller\AdminController::adminIndex

adminEdit:
  path: /admin/edit
  controller: App\Controller\AdminController::edit

adminDelete:
  path: /admin/delete
  controller: App\Controller\AdminController::delete

adminAdd:
  path: /admin/add
  controller: App\Controller\AdminController::add

#######################################################